import React, { useState } from 'react';
import { call } from '../lib/api.js';
import { Card, Field, Btn, Msg, Tabs, useAction, useLoad } from '../components/ui.jsx';

const GUIDE = { 'Getting started': 'Pick a tool on the left, choose your files, adjust the options and press Start. Results are saved next to the original by default, or in the folder chosen in Settings. Existing files are never overwritten.', 'Video': 'Fast GPU re-encode (H.264) uses your graphics card when available, otherwise the CPU. Maximum compression (H.265) is slowest and smallest. Remux only repackages the video with no quality change, ideal for .ts to .mp4.', 'Audio': 'Convert to MP3, AAC, WAV or FLAC, compress to a chosen bitrate, or extract the audio track from a video.', 'Images (HEIC)': 'Converts HEIC and other images to JPG. Failures are listed per file and do not stop the batch.', 'PDF': 'Images to PDF keeps the order you set. Merge PDFs joins existing PDFs. Corrupt or encrypted PDFs are reported by name.', 'Media Vault': 'Lists every job with sizes and results. Removing a record never deletes your files.', 'Subscription and payment': 'Plans are set by the administrator. Online payments activate automatically after the gateway confirms them. Manual payments activate once an admin approves your transaction.', 'Troubleshooting': 'If a tool says your plan does not include it, check Account > Subscription. Offline use works for a limited time; connect to the internet to refresh. Still stuck? Use Report a bug.' };

export default function Help({ goto }) {
  const faq = useLoad(() => call('GET', '/api/help/faq').catch(() => ({ faq: [] })));
  return (<div className="max-w-3xl mx-auto p-6"><h1 className="text-xl font-semibold mb-4">Help</h1><div className="grid gap-3 mb-6">{Object.entries(GUIDE).map(([t, d]) => <details key={t} className="panel p-3"><summary className="cursor-pointer font-medium">{t}</summary><p className="mt-2" style={{ color: 'var(--mute)' }}>{d}</p></details>)}</div>
    {faq.data && faq.data.faq.length > 0 && <><h2 className="font-semibold mb-2">Frequently asked questions</h2><div className="grid gap-3">{faq.data.faq.map((f) => <details key={f._id} className="panel p-3"><summary className="cursor-pointer font-medium">{f.question}</summary><p className="mt-2" style={{ color: 'var(--mute)' }}>{f.answer}</p></details>)}</div></>}
    <div className="flex gap-2 mt-6"><Btn onClick={() => goto('contact')}>Contact us</Btn><Btn onClick={() => goto('bug')}>Report a bug</Btn></div></div>);
}
export function Contact({ session }) {
  const [f, setF] = useState({ name: (session && session.user && session.user.name) || '', email: (session && session.user && session.user.email) || '', subject: '', message: '' }); const [id, setId] = useState(''); const a = useAction(); const set = (k) => (e) => setF({ ...f, [k]: e.target.value });
  return (<div className="max-w-xl mx-auto p-6"><h1 className="text-xl font-semibold mb-4">Contact us</h1>{id ? <Card><Msg kind="ok">Message sent. Your ticket number is {id}. We emailed you a confirmation.</Msg></Card> :
    <Card><form className="grid gap-3" onSubmit={async (e) => { e.preventDefault(); const r = await a.run(() => call('POST', '/api/contact', f)); if (r) setId(r.ticketId); }}><Field label="Name"><input value={f.name} onChange={set('name')} required /></Field><Field label="Email"><input type="email" value={f.email} onChange={set('email')} required /></Field><Field label="Subject"><input value={f.subject} onChange={set('subject')} required /></Field><Field label="Message"><textarea rows={6} value={f.message} onChange={set('message')} required style={{ background: 'var(--bg)', color: 'var(--ink)', border: '1px solid var(--line)', borderRadius: 6, padding: 8 }} /></Field><Msg>{a.err}</Msg><Btn primary type="submit" disabled={a.busy}>Send message</Btn></form></Card>}</div>);
}
export function BugReport({ info }) {
  const [f, setF] = useState({ title: '', description: '', category: 'GENERAL', severity: 'MEDIUM', steps: '', expected: '', actual: '' }); const [id, setId] = useState(''); const a = useAction(); const shotAct = useAction();
  const [shot, setShot] = useState(null); const [attachLog, setAttachLog] = useState(false); const [logText, setLogText] = useState('');
  const set = (k) => (e) => setF({ ...f, [k]: e.target.value });
  const ta = { background: 'var(--bg)', color: 'var(--ink)', border: '1px solid var(--line)', borderRadius: 6, padding: 8 };
  const toggleLog = async (on) => { setAttachLog(on); if (on && !logText) setLogText((await window.mediaAPI.recentLog()).text); };
  return (<div className="max-w-xl mx-auto p-6"><h1 className="text-xl font-semibold mb-4">Report a bug</h1>{id ? <Card><Msg kind="ok">Thank you. Your report number is {id}.</Msg></Card> :
    <Card><form className="grid gap-3" onSubmit={async (e) => { e.preventDefault(); const body = Object.fromEntries(Object.entries({ ...f, appVersion: info && info.version, os: navigator.platform, screenshot: shot && shot.dataUrl, logExcerpt: attachLog ? logText : undefined }).filter(([, v]) => v)); const r = await a.run(() => call('POST', '/api/bugs', body)); if (r) setId(r.reportId); }}>
      <Field label="Title"><input value={f.title} onChange={set('title')} required /></Field><Field label="What happened?"><textarea rows={4} value={f.description} onChange={set('description')} required style={ta} /></Field>
      <div className="grid grid-cols-2 gap-3"><Field label="Category"><select value={f.category} onChange={set('category')}>{['GENERAL', 'VIDEO', 'AUDIO', 'IMAGES', 'PDF', 'PAYMENT', 'ACCOUNT'].map((c) => <option key={c}>{c}</option>)}</select></Field><Field label="Severity"><select value={f.severity} onChange={set('severity')}>{['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].map((c) => <option key={c}>{c}</option>)}</select></Field></div>
      <Field label="Steps to reproduce"><textarea rows={3} value={f.steps} onChange={set('steps')} style={ta} /></Field><Field label="Expected"><input value={f.expected} onChange={set('expected')} /></Field><Field label="Actual"><input value={f.actual} onChange={set('actual')} /></Field>
      <div className="grid gap-2"><div className="flex items-center gap-2"><Btn type="button" disabled={shotAct.busy} onClick={async () => { const r = await shotAct.run(() => window.mediaAPI.prepareScreenshot()); if (r) setShot(r); }}>Attach screenshot</Btn>{shot && <><span className="text-sm">{shot.name} ({Math.round(shot.bytes / 1024)} KB)</span><Btn type="button" onClick={() => setShot(null)}>Remove</Btn></>}</div>{shot && <img src={shot.dataUrl} alt="Screenshot preview" className="max-h-40 rounded" style={{ border: '1px solid var(--line)' }} />}<Msg>{shotAct.err}</Msg>
        <label className="text-sm"><input type="checkbox" checked={attachLog} onChange={(e) => toggleLog(e.target.checked)} /> Attach recent diagnostic log</label>{attachLog && <details className="text-xs"><summary className="cursor-pointer">Review what will be sent</summary><pre className="overflow-auto max-h-40 p-2 mt-1" style={{ background: 'var(--bg)' }}>{logText}</pre></details>}</div>
      <p className="text-xs" style={{ color: 'var(--mute)' }}>App version {info ? info.version : ''} and your operating system are included automatically. Nothing else is sent unless you attach it above.</p><Msg>{a.err}</Msg><Btn primary type="submit" disabled={a.busy}>Send report</Btn></form></Card>}</div>);
}
