import React, { useState } from 'react';
import { call, money, date, FEATURE_LABELS } from '../../lib/api.js';
import { Card, Field, Btn, Msg, Chip, useAction, useLoad } from '../../components/ui.jsx';

const ta = { background: 'var(--bg)', color: 'var(--ink)', border: '1px solid var(--line)', borderRadius: 6, padding: 8 };
const numOrNull = (v) => (v === '' || v == null ? null : Number(v));

// ---------------- Plans ----------------
const blankPlan = () => ({ name: '', slug: '', description: '', price: '0', currency: 'BDT', isLifetime: false, billingPeriodDays: '30', rank: 1, sortOrder: 0, active: true, visible: true, oneTimePerUser: false, features: {}, limits: { dailyJobs: '', monthlyJobs: '', maxFileSizeMB: '' } });
const fromPlan = (p) => ({ ...blankPlan(), ...p, price: String(p.priceMinor / 100), billingPeriodDays: String(p.billingPeriodDays || 30), description: p.description || '', features: { ...(p.entitlements && p.entitlements.features) }, limits: { dailyJobs: p.entitlements.limits.dailyJobs ?? '', monthlyJobs: p.entitlements.limits.monthlyJobs ?? '', maxFileSizeMB: p.entitlements.limits.maxFileSizeMB ?? '' } });
const toBody = (f, updatedAt) => ({ name: f.name, slug: f.slug, description: f.description || undefined, priceMinor: Math.round(Number(f.price) * 100), currency: f.currency, isLifetime: f.isLifetime, billingPeriodDays: f.isLifetime ? undefined : Number(f.billingPeriodDays), rank: Number(f.rank), sortOrder: Number(f.sortOrder), active: f.active, visible: f.visible, oneTimePerUser: f.oneTimePerUser,
  entitlements: { features: Object.fromEntries(Object.keys(FEATURE_LABELS).map((k) => [k, !!f.features[k]])), limits: { dailyJobs: numOrNull(f.limits.dailyJobs), monthlyJobs: numOrNull(f.limits.monthlyJobs), maxFileSizeMB: numOrNull(f.limits.maxFileSizeMB) } }, expectedUpdatedAt: updatedAt });

export function PlanEditor() {
  const { data, err, reload } = useLoad(() => call('GET', '/api/admin/plans')); const [f, setF] = useState(null); const [editing, setEditing] = useState(null); const a = useAction();
  const set = (k) => (e) => setF({ ...f, [k]: e.target.type === 'checkbox' ? e.target.checked : e.target.value });
  const save = async (e) => { e.preventDefault(); if (await a.run(() => editing ? call('PUT', `/api/admin/plans/${editing._id}`, toBody(f, editing.updatedAt)) : call('POST', '/api/admin/plans', toBody(f)))) { setF(null); setEditing(null); reload(); } };
  const toggle = (p) => a.run(async () => { await call('PUT', `/api/admin/plans/${p._id}`, toBody({ ...fromPlan(p), active: !p.active }, p.updatedAt)); reload(); });
  return (<div className="grid gap-4"><div><Btn primary onClick={() => { setF(blankPlan()); setEditing(null); }}>New plan</Btn></div><Msg>{err || a.err}</Msg>
    {f && <Card title={editing ? `Edit ${editing.name}` : 'New plan'}><form onSubmit={save} className="grid gap-3">
      <div className="grid md:grid-cols-3 gap-3"><Field label="Name"><input value={f.name} onChange={set('name')} required /></Field><Field label="Slug (unique)"><input value={f.slug} onChange={set('slug')} required pattern="[a-z0-9-]+" /></Field><Field label="Order"><input type="number" value={f.sortOrder} onChange={set('sortOrder')} /></Field></div>
      <Field label="Description"><textarea rows={2} value={f.description} onChange={set('description')} style={ta} /></Field>
      <div className="grid md:grid-cols-4 gap-3"><Field label="Price (0 = free)"><input type="number" min="0" step="0.01" value={f.price} onChange={set('price')} required /></Field><Field label="Currency"><input value={f.currency} maxLength={3} onChange={set('currency')} /></Field><Field label="Days (billing period)"><input type="number" min="1" value={f.billingPeriodDays} onChange={set('billingPeriodDays')} disabled={f.isLifetime} /></Field><Field label="Rank (higher = stronger)"><input type="number" value={f.rank} onChange={set('rank')} /></Field></div>
      <div className="flex flex-wrap gap-4 text-sm">{[['isLifetime', 'Lifetime (never expires)'], ['active', 'Enabled'], ['visible', 'Visible to users'], ['oneTimePerUser', 'Once per account']].map(([k, l]) => <label key={k}><input type="checkbox" checked={f[k]} onChange={set(k)} /> {l}</label>)}</div>
      <fieldset><legend className="text-sm mb-1" style={{ color: 'var(--mute)' }}>Features included</legend><div className="grid grid-cols-2 md:grid-cols-3 gap-1">{Object.entries(FEATURE_LABELS).map(([k, l]) => <label key={k} className="text-sm"><input type="checkbox" checked={!!f.features[k]} onChange={(e) => setF({ ...f, features: { ...f.features, [k]: e.target.checked } })} /> {l}</label>)}</div></fieldset>
      <div className="grid md:grid-cols-3 gap-3">{[['dailyJobs', 'Jobs per day'], ['monthlyJobs', 'Jobs per month'], ['maxFileSizeMB', 'Max file size (MB)']].map(([k, l]) => <Field key={k} label={l} hint="Empty = unlimited"><input type="number" min="0" value={f.limits[k]} onChange={(e) => setF({ ...f, limits: { ...f.limits, [k]: e.target.value } })} /></Field>)}</div>
      <div className="panel p-3 text-sm"><strong>Preview:</strong> {f.name || 'Plan'}, {Number(f.price) === 0 ? 'Free' : money(Math.round(Number(f.price) * 100), f.currency)} {f.isLifetime ? '(lifetime)' : `/ ${f.billingPeriodDays} days`}<br />{Object.keys(FEATURE_LABELS).filter((k) => f.features[k]).map((k) => FEATURE_LABELS[k]).join(', ') || 'No features selected'}</div>
      <div className="flex gap-2"><Btn primary type="submit" disabled={a.busy}>Save plan</Btn><Btn type="button" onClick={() => { setF(null); setEditing(null); }}>Cancel</Btn></div></form></Card>}
    <div className="panel overflow-x-auto"><table className="w-full text-sm text-left"><thead style={{ color: 'var(--mute)' }}><tr><th className="p-2">Plan</th><th>Price</th><th>Term</th><th>State</th><th /></tr></thead><tbody>{data && data.items.map((p) => <tr key={p._id} style={{ borderTop: '1px solid var(--line)' }}><td className="p-2">{p.name} <span style={{ color: 'var(--mute)' }}>{p.slug}</span></td><td>{p.priceMinor === 0 ? 'Free' : money(p.priceMinor, p.currency)}</td><td>{p.isLifetime ? 'Lifetime' : `${p.billingPeriodDays} days`}</td><td>{p.archivedAt ? <Chip>archived</Chip> : p.active ? <Chip tone="ok">enabled</Chip> : <Chip tone="bad">disabled</Chip>}</td>
      <td className="flex gap-1 p-1"><Btn onClick={() => { setEditing(p); setF(fromPlan(p)); }}>Edit</Btn>{!p.archivedAt && <Btn onClick={() => toggle(p)}>{p.active ? 'Disable' : 'Enable'}</Btn>}{!p.archivedAt && <Btn onClick={() => window.confirm('Archive this plan? Existing subscribers keep their access.') && a.run(async () => { await call('POST', `/api/admin/plans/${p._id}/archive`); reload(); })}>Archive</Btn>}</td></tr>)}</tbody></table></div></div>);
}

// ---------------- Discounts ----------------
const localDT = (d) => (d ? new Date(d).toISOString().slice(0, 16) : '');
const blankDisc = () => ({ code: '', type: 'PERCENT', value: '10', enabled: true, startsAt: '', endsAt: '', planIds: [], maxRedemptions: '', perUserLimit: 1 });
export function DiscountEditor() {
  const { data, err, reload } = useLoad(() => call('GET', '/api/admin/discounts')); const plans = useLoad(() => call('GET', '/api/admin/plans')); const [f, setF] = useState(null); const [editing, setEditing] = useState(null); const a = useAction();
  const set = (k) => (e) => setF({ ...f, [k]: e.target.type === 'checkbox' ? e.target.checked : e.target.value });
  const body = () => ({ code: f.code, type: f.type, value: f.type === 'FIXED' ? Math.round(Number(f.value) * 100) : Number(f.value), enabled: f.enabled, startsAt: f.startsAt ? new Date(f.startsAt).toISOString() : null, endsAt: f.endsAt ? new Date(f.endsAt).toISOString() : null, planIds: f.planIds, maxRedemptions: f.maxRedemptions === '' ? null : Number(f.maxRedemptions), perUserLimit: Number(f.perUserLimit) });
  const save = async (e) => { e.preventDefault(); if (await a.run(() => editing ? call('PUT', `/api/admin/discounts/${editing._id}`, body()) : call('POST', '/api/admin/discounts', body()))) { setF(null); setEditing(null); reload(); } };
  const edit = (d) => { setEditing(d); setF({ ...blankDisc(), ...d, value: String(d.type === 'FIXED' ? d.value / 100 : d.value), startsAt: localDT(d.startsAt), endsAt: localDT(d.endsAt), maxRedemptions: d.maxRedemptions ?? '', planIds: (d.planIds || []).map(String) }); };
  return (<div className="grid gap-4"><div><Btn primary onClick={() => { setF(blankDisc()); setEditing(null); }}>New discount</Btn></div><Msg>{err || a.err}</Msg>
    {f && <Card title={editing ? `Edit ${editing.code}` : 'New discount'}><form onSubmit={save} className="grid gap-3">
      <div className="grid md:grid-cols-3 gap-3"><Field label="Code"><input value={f.code} onChange={(e) => setF({ ...f, code: e.target.value.toUpperCase() })} required /></Field><Field label="Type"><select value={f.type} onChange={set('type')}><option value="PERCENT">Percentage</option><option value="FIXED">Fixed amount</option></select></Field><Field label={f.type === 'PERCENT' ? 'Percent (1-100)' : 'Amount off'}><input type="number" step="0.01" min="0" value={f.value} onChange={set('value')} required /></Field></div>
      <div className="grid md:grid-cols-2 gap-3"><Field label="Starts (optional)"><input type="datetime-local" value={f.startsAt} onChange={set('startsAt')} /></Field><Field label="Ends (optional)"><input type="datetime-local" value={f.endsAt} onChange={set('endsAt')} /></Field></div>
      <div className="grid md:grid-cols-2 gap-3"><Field label="Total uses" hint="Empty = unlimited"><input type="number" min="1" value={f.maxRedemptions} onChange={set('maxRedemptions')} /></Field><Field label="Uses per user"><input type="number" min="1" value={f.perUserLimit} onChange={set('perUserLimit')} /></Field></div>
      <fieldset><legend className="text-sm" style={{ color: 'var(--mute)' }}>Applies to (none selected = all plans)</legend>{plans.data && plans.data.items.map((p) => <label key={p._id} className="mr-4 text-sm"><input type="checkbox" checked={f.planIds.includes(p._id)} onChange={(e) => setF({ ...f, planIds: e.target.checked ? [...f.planIds, p._id] : f.planIds.filter((x) => x !== p._id) })} /> {p.name}</label>)}</fieldset>
      <label className="text-sm"><input type="checkbox" checked={f.enabled} onChange={set('enabled')} /> Enabled</label><div className="flex gap-2"><Btn primary type="submit" disabled={a.busy}>Save discount</Btn><Btn type="button" onClick={() => { setF(null); setEditing(null); }}>Cancel</Btn></div></form></Card>}
    <div className="panel overflow-x-auto"><table className="w-full text-sm text-left"><thead style={{ color: 'var(--mute)' }}><tr><th className="p-2">Code</th><th>Value</th><th>Used</th><th>Remaining</th><th>Valid</th><th>State</th><th /></tr></thead><tbody>{data && data.items.map((d) => <tr key={d._id} style={{ borderTop: '1px solid var(--line)' }}><td className="p-2">{d.code}</td><td>{d.type === 'PERCENT' ? `${d.value}%` : money(d.value)}</td><td>{d.redeemedCount}</td><td>{d.remaining ?? '∞'}</td><td>{date(d.startsAt)} → {date(d.endsAt)}</td><td>{d.enabled ? <Chip tone="ok">enabled</Chip> : <Chip tone="bad">disabled</Chip>}</td><td className="flex gap-1 p-1"><Btn onClick={() => edit(d)}>Edit</Btn><Btn onClick={() => a.run(async () => { await call('PUT', `/api/admin/discounts/${d._id}`, { code: d.code, type: d.type, value: d.value, enabled: !d.enabled, startsAt: d.startsAt || null, endsAt: d.endsAt || null, planIds: (d.planIds || []).map(String), maxRedemptions: d.maxRedemptions ?? null, perUserLimit: d.perUserLimit }); reload(); })}>{d.enabled ? 'Disable' : 'Enable'}</Btn><Btn onClick={() => window.confirm('Delete this discount?') && a.run(async () => { await call('DELETE', `/api/admin/discounts/${d._id}`); reload(); })}>Delete</Btn></td></tr>)}</tbody></table></div></div>);
}

// ---------------- MFS ----------------
export function MfsEditor() {
  const { data, err, reload } = useLoad(() => call('GET', '/api/admin/mfs')); const [f, setF] = useState(null); const [editing, setEditing] = useState(null); const a = useAction(); const set = (k) => (e) => setF({ ...f, [k]: e.target.type === 'checkbox' ? e.target.checked : e.target.value });
  const save = async (e) => { e.preventDefault(); const b = { name: f.name, accountNumber: f.accountNumber, accountType: f.accountType, instructions: f.instructions || undefined, enabled: f.enabled, sortOrder: Number(f.sortOrder) }; if (await a.run(() => editing ? call('PUT', `/api/admin/mfs/${editing._id}`, b) : call('POST', '/api/admin/mfs', b))) { setF(null); setEditing(null); reload(); } };
  const move = (i, d) => { const ids = data.items.map((x) => x._id); [ids[i], ids[i + d]] = [ids[i + d], ids[i]]; a.run(async () => { await call('POST', '/api/admin/mfs/reorder', { ids }); reload(); }); };
  return (<div className="grid gap-4"><div><Btn primary onClick={() => { setF({ name: '', accountNumber: '', accountType: 'PERSONAL', instructions: '', enabled: true, sortOrder: 0 }); setEditing(null); }}>Add MFS account</Btn></div><Msg>{err || a.err}</Msg>
    {f && <Card title={editing ? 'Edit MFS account' : 'Add MFS account'}><form onSubmit={save} className="grid gap-3 max-w-lg"><Field label="Name (e.g. bKash)"><input value={f.name} onChange={set('name')} required /></Field><Field label="Account number"><input value={f.accountNumber} onChange={set('accountNumber')} inputMode="tel" required /></Field><Field label="Account type"><select value={f.accountType} onChange={set('accountType')}><option>PERSONAL</option><option>AGENT</option><option>MERCHANT</option></select></Field><Field label="Instructions shown to users"><textarea rows={3} value={f.instructions} onChange={set('instructions')} style={ta} /></Field><label className="text-sm"><input type="checkbox" checked={f.enabled} onChange={set('enabled')} /> Enabled</label><div className="flex gap-2"><Btn primary type="submit" disabled={a.busy}>Save</Btn><Btn type="button" onClick={() => { setF(null); setEditing(null); }}>Cancel</Btn></div></form></Card>}
    {data && data.items.map((m, i) => <div key={m._id} className="panel p-3 flex justify-between items-center"><div><strong>{m.name}</strong> {m.accountNumber} <Chip>{m.accountType}</Chip> {m.enabled ? <Chip tone="ok">enabled</Chip> : <Chip tone="bad">disabled</Chip>}</div><div className="flex gap-1"><Btn disabled={i === 0} aria-label="Move up" onClick={() => move(i, -1)}>↑</Btn><Btn disabled={i === data.items.length - 1} aria-label="Move down" onClick={() => move(i, 1)}>↓</Btn><Btn onClick={() => { setEditing(m); setF({ ...m, instructions: m.instructions || '' }); }}>Edit</Btn><Btn onClick={() => window.confirm('Remove this account?') && a.run(async () => { await call('DELETE', `/api/admin/mfs/${m._id}`); reload(); })}>Remove</Btn></div></div>)}</div>);
}

// ---------------- FAQ ----------------
export function FaqEditor() {
  const { data, err, reload } = useLoad(() => call('GET', '/api/admin/faq')); const [f, setF] = useState(null); const [editing, setEditing] = useState(null); const a = useAction(); const set = (k) => (e) => setF({ ...f, [k]: e.target.type === 'checkbox' ? e.target.checked : e.target.value });
  const save = async (e) => { e.preventDefault(); const b = { category: f.category, question: f.question, answer: f.answer, published: f.published, sortOrder: Number(f.sortOrder) }; if (await a.run(() => editing ? call('PUT', `/api/admin/faq/${editing._id}`, b) : call('POST', '/api/admin/faq', b))) { setF(null); setEditing(null); reload(); } };
  return (<div className="grid gap-4"><div><Btn primary onClick={() => { setF({ category: 'general', question: '', answer: '', published: true, sortOrder: 0 }); setEditing(null); }}>New FAQ</Btn></div><Msg>{err || a.err}</Msg>
    {f && <Card title="FAQ entry"><form onSubmit={save} className="grid gap-3 max-w-xl"><Field label="Category"><input value={f.category} onChange={set('category')} /></Field><Field label="Question"><input value={f.question} onChange={set('question')} required /></Field><Field label="Answer"><textarea rows={4} value={f.answer} onChange={set('answer')} required style={ta} /></Field><label className="text-sm"><input type="checkbox" checked={f.published} onChange={set('published')} /> Published</label><div className="flex gap-2"><Btn primary type="submit" disabled={a.busy}>Save</Btn><Btn type="button" onClick={() => { setF(null); setEditing(null); }}>Cancel</Btn></div></form></Card>}
    {data && data.items.map((q) => <div key={q._id} className="panel p-3 flex justify-between gap-3"><div><Chip>{q.category}</Chip> <strong>{q.question}</strong>{!q.published && <Chip tone="bad">hidden</Chip>}<p className="text-sm mt-1" style={{ color: 'var(--mute)' }}>{q.answer}</p></div><div className="flex gap-1"><Btn onClick={() => { setEditing(q); setF({ ...q }); }}>Edit</Btn><Btn onClick={() => window.confirm('Delete this FAQ?') && a.run(async () => { await call('DELETE', `/api/admin/faq/${q._id}`); reload(); })}>Delete</Btn></div></div>)}</div>);
}
